version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: students_db
    restart: always
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
